# Light theme
[theme]
name = "light"
base = "light"
primaryColor = "#E694FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Dark theme
[theme]
name = "dark"
base = "dark"
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans serif"
